CREATE TABLE IF NOT EXISTS user_profiles (
    id TEXT PRIMARY KEY,
    google_sub TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    invite_token TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    social_url TEXT NOT NULL DEFAULT '',
    background TEXT NOT NULL DEFAULT '',
    picture_url TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_login_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS house_events (
    id TEXT PRIMARY KEY,
    public_token TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    starts_at TEXT NOT NULL,
    ends_at TEXT NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT TRUE,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS applications (
    id TEXT PRIMARY KEY,
    public_token TEXT NOT NULL UNIQUE,
    user_profile_id TEXT REFERENCES user_profiles(id) ON DELETE SET NULL,
    sponsor_profile_id TEXT REFERENCES user_profiles(id) ON DELETE SET NULL,
    house_event_id TEXT REFERENCES house_events(id) ON DELETE SET NULL,
    sponsor_approved_at TEXT,
    kind TEXT NOT NULL CHECK (kind IN ('visitor', 'temporary_resident', 'long_term_resident', 'event')),
    status TEXT NOT NULL CHECK (status IN (
        'submitted', 'under_review', 'interview_scheduled',
        'interview_completed', 'approved', 'rejected', 'withdrawn'
    )),
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    social_url TEXT NOT NULL DEFAULT '',
    purpose TEXT NOT NULL,
    background TEXT NOT NULL DEFAULT '',
    referral TEXT NOT NULL DEFAULT '',
    event_name TEXT NOT NULL DEFAULT '',
    requested_start TEXT,
    requested_end TEXT,
    interview_required BOOLEAN NOT NULL DEFAULT FALSE,
    applicant_message TEXT NOT NULL DEFAULT '',
    admin_notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    decided_at TEXT
);

CREATE INDEX IF NOT EXISTS applications_status_idx ON applications(status, created_at DESC);
CREATE INDEX IF NOT EXISTS applications_kind_idx ON applications(kind, created_at DESC);

CREATE TABLE IF NOT EXISTS interviews (
    id TEXT PRIMARY KEY,
    application_id TEXT NOT NULL UNIQUE REFERENCES applications(id) ON DELETE CASCADE,
    scheduled_at TEXT NOT NULL,
    location TEXT NOT NULL,
    interviewer TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL CHECK (status IN ('scheduled', 'completed', 'cancelled')),
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pin_grants (
    id TEXT PRIMARY KEY,
    application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    lock_name TEXT NOT NULL,
    access_code_id TEXT,
    access_code_name TEXT NOT NULL,
    pin_ciphertext TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'revoked', 'failed')),
    error TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    revoked_at TEXT
);

CREATE INDEX IF NOT EXISTS pin_grants_application_idx ON pin_grants(application_id, created_at DESC);

CREATE TABLE IF NOT EXISTS application_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS application_events_application_idx
ON application_events(application_id, created_at DESC);
